### ISSUE TITLE
Stolen

### ISSUE THREAD

**Issue by oupirum** [ahmadawais/lerna-tutorial#4]
Repo stolen from https://github.com/reggi/lerna-tutorial, you didn't provide link to original author.

**Comment by ahmadawais** [comment]
Dang it. I meant to fork it and it looks like my automated workflow script committed it as my own work, which this clearly isn't. Let me address that and thank you for bringing this to my attention.

**Comment by ahmadawais** [comment]
I just fixed the readme, please take a stab at bettering it if you believe it can be, by creating a PR.
